spring.application.name=LunarStorage
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

app.database.type=${DATABASE_TYPE:postgresql}
app.secrets.tokens=${TOKENS_SECRET}

admin.user-id=${ADMIN_USER_ID}